name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLN_FILE: ${{ github.workspace }}/Chess.slnx
      PROJECT_FILE: ${{ github.workspace }}/src/Chess.UI/Chess.UI.csproj
      BUILD_OUTPUT_DIR: ${{ github.workspace }}/publish/INTERNAL/build
      TEST_RESULTS_DIR: ${{ github.workspace }}/publish/INTERNAL/TestResults
      TEST_RESULTS_FILE: test-results.trx
      ARTIFACT_NAME: build-output

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore $SLN_FILE

      - name: Build solution
        run: dotnet build --no-restore --configuration Release $SLN_FILE

      - name: Publish build output
        run: dotnet publish --no-build --configuration Release --property:PublishDir=$BUILD_OUTPUT_DIR $PROJECT_FILE

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_OUTPUT_DIR }}
          retention-days: 2

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_OUTPUT_DIR }}

      - name: Run tests
        run: |
          mkdir -p $TEST_RESULTS_DIR
          dotnet test --no-build --configuration Release --logger "trx;LogFileName=$TEST_RESULTS_FILE" --results-directory $TEST_RESULTS_DIR
        continue-on-error: true

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: ${{ env.TEST_RESULTS_DIR }}/${{ env.TEST_RESULTS_FILE }}
